export const SET_USER_DATA = "SET_USER_DATA";
export const SET_IS_AUTHENTICATE = "SET_IS_AUTHENTICATE";
export const SET_NOTIFICATION_MESSAGE = "SET_NOTIFICATION_MESSAGE";
export const SET_IS_CART_UPDATE = "SET_IS_CART_UPDATE";